const words=[
    {text:'C',value:1,type:1},
    {text:'Javascript',value:1,type:2},
    {text:'C#',value:2,type:5},
    {text:'C++',value:2,type:1},
    {text:'Python',value:3,type:3},
    {text:'Java',value:3,type:4},
    {text:'React',value:4,type:2},
    {text:'Angular',value:4,type:5},
    {text:'Node.js',value:5,type:1},
    {text:'공부',value:1,type:1},
    {text:'월급',value:1,type:2},
    {text:'직장',value:2,type:5},
    {text:'데이트',value:2,type:1},
    {text:'연애',value:3,type:3},
    {text:'여자친구',value:3,type:4},
    {text:'남자친구',value:4,type:2},
    {text:'미세먼지',value:4,type:5},
    {text:'돈',value:5,type:1},
    {text:'건강',value:1,type:1},
    {text:'코로나 바이러스',value:1,type:2},
    {text:'부모님',value:2,type:5},
    {text:'커피',value:2,type:1},
    {text:'책상',value:3,type:3},
    {text:'의자',value:3,type:4},
    {text:'인공지능 실습',value:4,type:2},
    {text:'중간고사',value:4,type:5},
    {text:'기말고사',value:5,type:1},
];

export default words;